In [25]:
import numpy as np
from numpy import pi
a=np.arange(15).reshape(3,5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.size

15

In [7]:
a.dtype.name

'int64'

In [8]:
a.itemsize

8

In [9]:
a.size

15

In [10]:
type(a)


numpy.ndarray

In [12]:
b=np.array([(1,2,6),(3,4,5)])
b

array([[1, 2, 6],
       [3, 4, 5]])

In [16]:
b=np.array([[1,2,6],[3,4,5]],dtype=complex)
b

array([[1.+0.j, 2.+0.j, 6.+0.j],
       [3.+0.j, 4.+0.j, 5.+0.j]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((5,6),dtype=np.int16)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int16)

In [22]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [24]:
np.arange(0,3,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [26]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [29]:
x=np.linspace(0,2*pi,100)
np.sin(x)

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [30]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [32]:
a=np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [33]:
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [34]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a-b
c

array([20, 29, 38, 47])

In [35]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [36]:
c<35

array([ True,  True, False, False])

In [37]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])


#### ELEMENTWISE PRODUCT

In [39]:
A*B

array([[2, 0],
       [0, 4]])

#### MATRIX PRODUCT

In [40]:
A@B

array([[5, 4],
       [3, 4]])

In [41]:
A.dot(B)

array([[5, 4],
       [3, 4]])

###### Some operations, such as += and *=, act in place to modify an existing array rather than create a new one

In [51]:
rg=np.random.default_rng(1) #default random number generator

a=np.ones((2,3),dtype=int)
b=rg.random((2,3))
print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [52]:
a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [53]:
b+=a 
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [54]:
a+=b #b is not automatically converted to int and therefore aa casting rule'same kind' error
a

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [65]:
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,pi,3)
b.dtype.name

'float64'

In [66]:
c=a+b
print(c)
c.dtype.name

[1.         2.57079633 4.14159265]


'float64'

In [69]:
d=np.exp(c*1j)
print(d)
print(d.dtype.name)

[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


In [70]:
a=rg.random((2,3))
print(a)
print('a.sum:',a.sum())
print('a minimum :',a.min())
print('a maximum:',a.max())

[[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]
a.sum: 3.1057109529998157
a minimum : 0.027559113243068367
a maximum: 0.8277025938204418
